enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: $NPM_AUTH_TOKEN

#npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  gen2tech:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

# logFilters:
#   - code: "YN0035"
#     level: "discard"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
