on:
  push:
    branches: main
name: Publish wc-hash-router
jobs:
  publish:
    #environment: CI
    CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - run: mkdir dist
      - run: mkdir transpiled
      - run: yarn install
      - run: yarn build
      - run: yarn deploy
      - run: |
          echo TOKEN-IS: '${secrets.NPM_AUTH_TOKEN}'